-- Seed factories (run after 001_create_factories.sql)
insert into public.factories (name, is_verified, products, location, district, whatsapp, email, phone, machinery, status, industry, certifications, about, capacity, established) values
('Colombo Stitchworks', false, '[{"name":"T-Shirts","moq":100},{"name":"Hoodies","moq":250},{"name":"Polo Shirts","moq":150}]', 'Biyagama Export Zone', 'Gampaha', '94771234567', 'sales@colombostitchworks.lk', '+94 11 234 5678', '["Single Needle x20","Overlock x5","Flatlock x3"]', 'Community Sourced', 'Apparel', '["ISO 9001"]', 'Colombo Stitchworks is a mid-sized garment manufacturer specializing in casual wear and sportswear. We have been serving local and international brands since 2008.', '15,000 pieces/month', 2008),
('Lanka Garments International', true, '[{"name":"Denim Jeans","moq":500},{"name":"Shorts","moq":300},{"name":"Jackets","moq":400}]', 'Katunayake FTZ', 'Gampaha', '94772345678', 'info@lankagarments.com', '+94 11 345 6789', '["Denim Washing x2","Heavy Duty Sewing x15","Button Attach x8"]', 'Verified', 'Apparel', '["ISO 9001","ISO 14001","Fair Trade"]', 'Lanka Garments International is a leading denim manufacturer with state-of-the-art washing facilities. We export to major European and American brands.', '50,000 pieces/month', 1995),
('Ceylon Rubber Products', true, '[{"name":"Rubber Gloves","moq":10000},{"name":"Industrial Seals","moq":5000},{"name":"Rubber Mats","moq":1000}]', 'Horana Industrial Zone', 'Kalutara', '94773456789', 'export@ceylonrubber.lk', '+94 34 226 7890', '["Vulcanizing Press x4","Mixing Mill x2","Injection Moulding x6"]', 'Verified', 'Rubber', '["ISO 9001","SLS"]', 'Ceylon Rubber Products has been manufacturing high-quality rubber products for over 40 years. Our products are exported to 25+ countries worldwide.', '100,000 units/month', 1982),
('Kandy Tea Exports', true, '[{"name":"Black Tea (Bulk)","moq":1000},{"name":"Green Tea Bags","moq":5000},{"name":"Specialty Tea","moq":500}]', 'Kandy Industrial Estate', 'Kandy', '94774567890', 'orders@kandytea.com', '+94 81 234 5678', '["Tea Rolling x8","Drying Chamber x4","Packaging Line x2"]', 'Verified', 'Tea', '["ISO 22000","Fair Trade","Rainforest Alliance"]', 'Kandy Tea Exports sources premium Ceylon tea from the highlands. We offer private labeling and custom blending services for international markets.', '20,000 kg/month', 1975),
('Southern Textiles Mills', false, '[{"name":"Cotton Fabric","moq":2000},{"name":"Polyester Blend","moq":3000},{"name":"Jersey Knit","moq":1500}]', 'Koggala FTZ', 'Galle', '94775678901', 'sales@southerntextiles.lk', '+94 91 345 6789', '["Circular Knitting x12","Dyeing Vats x6","Finishing Line x2"]', 'Community Sourced', 'Textiles', '["ISO 9001"]', 'Southern Textiles Mills is a vertical textile manufacturer producing high-quality fabrics for the apparel industry. We specialize in knitted fabrics.', '80,000 meters/month', 2001),
('Negombo Fashion Factory', false, '[{"name":"Swimwear","moq":200},{"name":"Activewear","moq":150},{"name":"Lingerie","moq":300}]', 'Negombo Industrial Area', 'Gampaha', '94776789012', 'info@negombofashion.com', '+94 31 456 7890', '["Specialized Sewing x25","Bonding Machine x4","Heat Press x6"]', 'Community Sourced', 'Apparel', '["OEKO-TEX"]', 'Negombo Fashion Factory specializes in intimate apparel and swimwear manufacturing with expertise in delicate fabrics and specialized construction techniques.', '25,000 pieces/month', 2010),
('Ratnapura Gem Polishing', true, '[{"name":"Blue Sapphires","moq":10},{"name":"Rubies","moq":5},{"name":"Semi-precious Stones","moq":50}]', 'Ratnapura Town', 'Ratnapura', '94777890123', 'gems@ratnapuragems.lk', '+94 45 222 3456', '["Gem Cutting x10","Polishing Wheel x15","Grading Equipment x3"]', 'Verified', 'Gems', '["SLS","GIA Certified"]', 'Ratnapura Gem Polishing is a family-owned business with three generations of expertise in cutting and polishing Ceylon gems to international standards.', '500 carats/month', 1965),
('Jaffna Coir Industries', false, '[{"name":"Coir Mats","moq":500},{"name":"Coir Rope","moq":1000},{"name":"Coir Fiber","moq":2000}]', 'Jaffna Industrial Estate', 'Jaffna', '94778901234', 'export@jaffnacoir.com', '+94 21 234 5678', '["Fiber Extraction x4","Spinning Machine x8","Weaving Loom x6"]', 'Community Sourced', 'Coir', '["ISO 9001"]', 'Jaffna Coir Industries produces eco-friendly coir products using traditional methods combined with modern quality control standards.', '30,000 kg/month', 1998),
('Kurunegala Ceramics', true, '[{"name":"Tableware Sets","moq":100},{"name":"Decorative Items","moq":50},{"name":"Tiles","moq":500}]', 'Kurunegala Industrial Zone', 'Kurunegala', '94779012345', 'sales@kurceramics.lk', '+94 37 222 3456', '["Kiln x3","Pottery Wheel x20","Glazing Station x8"]', 'Verified', 'Ceramics', '["ISO 9001","SLS"]', 'Kurunegala Ceramics combines traditional Sri Lankan pottery techniques with modern design to create unique ceramic products for export markets.', '10,000 pieces/month', 1988),
('Trinco Seafood Processing', false, '[{"name":"Frozen Prawns","moq":500},{"name":"Dried Fish","moq":1000},{"name":"Canned Tuna","moq":2000}]', 'Trincomalee Harbor Area', 'Trincomalee', '94770123456', 'orders@trincoseafood.com', '+94 26 234 5678', '["Flash Freezer x2","Processing Line x4","Canning Machine x2"]', 'Community Sourced', 'Food Processing', '["ISO 22000","HACCP"]', 'Trinco Seafood Processing sources fresh catch from local fishermen and processes them to international food safety standards for export.', '50,000 kg/month', 2005);
