-- Manufacturing.lk factories table
create table if not exists public.factories (
  id bigint generated by default as identity primary key,
  name text not null,
  is_verified boolean default false,
  products jsonb default '[]'::jsonb,
  location text not null,
  district text not null,
  whatsapp text,
  email text,
  phone text,
  machinery jsonb default '[]'::jsonb,
  status text check (status in ('Verified', 'Community Sourced')) default 'Community Sourced',
  industry text not null,
  certifications jsonb default '[]'::jsonb,
  about text,
  capacity text,
  established integer,
  created_at timestamptz default now()
);

-- Enable RLS
alter table public.factories enable row level security;

-- Allow public read access
create policy "Allow public read access"
  on public.factories for select
  using (true);

-- Allow authenticated users to insert/update/delete (for your admin use)
create policy "Allow authenticated insert"
  on public.factories for insert
  to authenticated
  with check (true);

create policy "Allow authenticated update"
  on public.factories for update
  to authenticated
  using (true);

create policy "Allow authenticated delete"
  on public.factories for delete
  to authenticated
  using (true);
